version: "3"
services:
  db1:
    image: "postgres:11"
    container_name: "my_postgres_1"
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root

  db2:
    image: "postgres:11"
    container_name: "my_postgres_2"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
 
  airflow:
    image: puckel/docker-airflow
    container_name: "airflow"
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/usr/local/airflow/operators/
    volumes:
      - /home/shamil/ETL-DWH_study/hw6/dags/:/usr/local/airflow/dags
      - /home/shamil/ETL-DWH_study/hw6/operators/:/usr/local/airflow/operators
    command: webserver

volumes:
  my_dbdata: 
