version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "target_pg"
    ports:
      - "5434:5432"
    volumes:
      - /home/shamil/ETL-DWH_study/target_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
